-- Added NoteDto
fasetto/devnots pull request #14
Opened 2020-08-12 23:24 UTC by AbdullahOztuurkk

-- Added Note Class
-- Added Note Repository
-- Added Note Validator
-- Added INoteDetails Interface
-- Added INoteRepository Interface
-- Added NoteCollection Class
-- Added NoteController

2020-08-12 23:28 UTC, fasetto commented
@AbdullahOztuurkk Koda henüz bakamadım ama, CI da build fail olmuş mesela. 
```
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  DevNots.Domain -> /home/runner/work/devnots/devnots/src/DevNots.Domain/bin/Release/netstandard2.0/DevNots.Domain.dll
##[error]MongoDbContext.cs(6,18): error CS0534: 'MongoDbContext' does not implement inherited abstract member 'DbContext.Notes.get' [/home/runner/work/devnots/devnots/src/DevNots.MongoDb/DevNots.MongoDb.csproj]

Build FAILED.

##[error]MongoDbContext.cs(6,18): error CS0534: 'MongoDbContext' does not implement inherited abstract member 'DbContext.Notes.get' [/home/runner/work/devnots/devnots/src/DevNots.MongoDb/DevNots.MongoDb.csproj]
```
Abstract class daki implement edilmesi gereken bir şeyi unutmuş olabilirsin diyor hata mesajında.
Şimdi kodu bi inceleyeyim.

2020-08-12 23:31 UTC, fasetto commented on src/DevNots.Application/Services/UserService.cs
>              }
Bunu yakaladığın iyi olmuş. (:

2020-08-12 23:32 UTC, fasetto commented on src/DevNots.Application/Validations/NoteValidator.cs
> +            RuleFor(rule => rule.Text).MinimumLength(1);
Burada minimum length yerine max length kullanırsak daha iyi olabilir. Ya da böyle de kalabilir bilemiyorum.

2020-08-12 23:33 UTC, fasetto commented on src/DevNots.Application/Contracts/NoteDto.cs
> +    public class NoteDto
INoteDetails interface ini implement etmeli burası

2020-08-12 23:34 UTC, fasetto commented on src/DevNots.Application/Services/NoteService.cs
> +namespace DevNots.Application.Services
Buradaki eksik olan methodları da eklemek istersen devam edebilirsin.

2020-08-12 23:36 UTC, fasetto commented on src/DevNots.Domain/Note/Note.cs
> +        public Note(int UserId,string Text,DateTime CreatedAt)
createdAt parametresi constructordan kaldırılmalı. Bu parametre otomatik olarak doldurulur kayıt yaparken Dto tarafında

2020-08-12 23:37 UTC, fasetto commented on src/DevNots.MongoDb/NoteCollection.cs
> +            var _note = await FindOneAsync(filter => filter.UserId == aggregate.UserId || filter.Text == aggregate.Text);
42. satırı aslında silebilirsin, hiç gerek yok buna.
`return aggregate.Id` şeklinde id döndürülmeli.

2020-08-12 23:39 UTC, AbdullahOztuurkk commented on src/DevNots.Domain/Note/Note.cs
> +        public Note(int UserId,string Text,DateTime CreatedAt)
PaginateAsync yapılmayacak mı?

2020-08-12 23:40 UTC, fasetto requested changes
Bahsettiğim değişiklikleri de yaparsın müsait olduğun da tekrar. 👍

2020-08-12 23:43 UTC, fasetto commented on src/DevNots.Domain/Note/Note.cs
> +        public Note(int UserId,string Text,DateTime CreatedAt)
Yapılacak fakat, createdAt property burada set etmek yerine NotDto da varsayılan olarak DateTime.UtcNow şeklinde atayabiliriz. 
Manuel olarak girmemiz gerekmez her defasında. (:

2020-08-13 07:07 UTC, fasetto requested changes

2020-08-13 07:07 UTC, fasetto commented on src/DevNots.Domain/Note/INoteDetails.cs
> +        public int UserId { get; set; }
UserId int değil de string tipinde olmalı. Çünki MongoDb de ObjectId tipinde tutuluyor aslında bu değer. Kod tarafında stringe dönüştürülüp o şekilde kullanıyoruz.

2020-08-13 07:07 UTC, fasetto commented on src/DevNots.Domain/Note/Note.cs
> +        public int UserId { get; set; }
Burası da aynı şekilde string tipinde olmalı.

2020-08-13 07:09 UTC, fasetto commented
Merge yapılmadan issue ları kapamıyoruz bu arada. Linklendiği zaman birbirine issue ve pull request, merge yapıldığı zaman otomatik olarak kapanıyor. 😅

2020-08-13 10:38 UTC, fasetto requested changes

2020-08-13 10:38 UTC, fasetto commented on src/DevNots.Application/Services/NoteService.cs
> +namespace DevNots.Application.Services
Bence bununu da tamamla, merge ettiğimiz zaman canlıda 🌐 her şey hazır halde olsun.

2020-08-13 10:38 UTC, fasetto commented on src/DevNots.Domain/Note/INoteDetails.cs
> +        public string Text { get; set; }
Burada olması gereken başka özellikler de var aslında. 
- [ ] Title
- [ ] Description gibi. 

Aklıma başka gelmedi ama eğer senin gelirse ekleyebilirsin (:
Bu arada interface de değişiklik yaptıktan sonra ilgili class ları düzenlemeyi unutma *(Note, NoteDto gibi)*

2020-08-13 11:53 UTC, fasetto approved these changes

2020-08-13 11:55 UTC, fasetto commented
@AbdullahOztuurkk Eline sağlık. Bitirdiysen merge yapabilirsin. 👍

2020-08-13 13:45 UTC, fasetto requested changes
Her şey düzgün görünüyor. Ama bir şey var unuttuğun, şimdi contructorlarda tanımladığımız bazı bağımlılıklar var.
Bunları da inject etmek için IoC container kullanıyoruz. *(Microsoft.Extensions.DependencyInjection nuget paketi)*
Bu bağımlılıkları Application katmanında Extensions klasörü içinde ServiceCollectionExtensions var. Orada tanımlaman gerekiyor. UserService için tanımlamıştım, incelersen aynı şekilde kodları notlar için de yazmak gerekiyor. 😄
Yoksa runtime da hata verir bağımlılıkları çözemediği için. 
Kolay gelsin.

Edit: [ServiceCollectionExtensions.cs](https://github.com/fasetto/devnots/blob/master/src/DevNots.Application/Extensions/ServiceCollectionExtensions.cs)

2020-08-13 14:24 UTC, AbdullahOztuurkk commented
> Her şey düzgün görünüyor. Ama bir şey var unuttuğun, şimdi contructorlarda tanımladığımız bazı bağımlılıklar var.
> Bunları da inject etmek için IoC container kullanıyoruz. _(Microsoft.Extensions.DependencyInjection nuget paketi)_
> Bu bağımlılıkları Application katmanında Extensions klasörü içinde ServiceCollectionExtensions var. Orada tanımlaman gerekiyor. UserService için tanımlamıştım, incelersen aynı şekilde kodları notlar için de yazmak gerekiyor. 😄
> Yoksa runtime da hata verir bağımlılıkları çözemediği için.
> Kolay gelsin.
> 
> Edit: [ServiceCollectionExtensions.cs](https://github.com/fasetto/devnots/blob/master/src/DevNots.Application/Extensions/ServiceCollectionExtensions.cs)

Gözden kaçırmışım pardon ::)
Hemen düzenleyip gönderiyorum

2020-08-13 14:53 UTC, fasetto approved these changes
Eline sağlık, merge yapabilirsin. 👍

2020-08-13 15:15 UTC, merged